name: Pulumi Up

on:
  push:
    branches: [main]

jobs:
  pulumi-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Build
        run: go build ./...
      - uses: pulumi/actions@v4
      - name: Pulumi Up
        run: pulumi login ${{ secrets.PULUMI_CLOUD_URL }}
      - name: Pulumi Up
        run: pulumi up --stack production --non-interactive --yes
    env:
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-west-2"
